### ISSUE TITLE
Misleading legend 

### ISSUE THREAD

**Issue by Pios15** [giacomoponzuoli3/KirunaExplorer#7]
You should change the misleading legend in the main page

**Comment by criicky** [comment]
In the adding new document form some of the data should be fetched from the db for example the languages

**Comment by giacomoponzuoli3** [comment]
I've taken on board feedback about the confusing legend on the main page and made a number of changes to improve clarity and usability.

1. I've removed anything that could create visual confusion and redesigned the legend to make it more intuitive.
2. I've added an icon to toggle the legend, placing it at the bottom left of the page so as not to interfere with the main content (currently without the map).
3. The legend itself is now visible in a modal that can be easily dismissed by clicking outside, keeping the interface clean and unobtrusive.
4. Each document type in the legend is now represented with a clear icon and descriptive label, improving understanding for the user.
